server:
  port: 8083

spring:
  profiles:
    include: db, mail
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false

eventuatelocal:
  kafka:
    bootstrap:
      servers: localhost:9092
  zookeeper:
    connection:
      string: localhost:2181

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    io.eventuate.SQL: debug
    io.eventuate.tram: TRACE
